account = "ARFPAGZ-XLB69922"
user = "OBSIDIAN"
password = "Staarlordsanthosh007"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = "TRUE"
